apiVersion: v1

kind: Service

metadata:
  name: myfirstservice
  labels: 
    servicelbl: labelname

spec: 
  type: LoadBalancer
  ports: 
    - nodePort: 30000
      port: 32000
      targetPort: 80
  selector:
    app: myapp