apiVersion: apps/v1

kind: ReplicaSet

metadata: 
  name: firstrs
  labels:
    name: firstrs


spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: firstpod
      labels:
        app: myapp
    spec:
      containers:
      - name: firstcontainer
        image: coolgourav147/nginx-custom