apiVersion: v1

kind: ReplicationController

metadata: 
  name: firstrc
  labels: 
    appname: voatingapp


spec:
  replicas: 5
  selector:
    type: app
  template:
    metadata:
      name: firstpod
      labels:
        type: app
    spec:
      containers:
      - image: coolgourav147/nginx-custom
        name: firstcontainer