apiVersion: v1

kind: Service

metadata:
  name: myfirstservice
  labels: 
    servicelbl: labelname

spec: 
  type: NodePort
  ports: 
    - nodePort: 32000
      port: 30000
      targetPort: 80
  selector:
    type: app